development:
  adapter: postgresql
  encoding: unicode
  database: ideas_development
  pool: 5
  username: kirk
  password: sd3472307

test:
  adapter: postgresql
  encoding: unicode
  database: ideas_test
  pool: 5
  username: kirk
  password: sd3472307

production:
  adapter: postgresql
  encoding: unicode
  database: ideas_production
  pool: 5
  username: kirk
  password: sd3472307